apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/metallb.io_ipaddresspools.yaml
- bases/metallb.io_bgppeers.yaml
- bases/metallb.io_bfdprofiles.yaml
- bases/metallb.io_bgpadvertisements.yaml
- bases/metallb.io_l2advertisements.yaml
- bases/metallb.io_communities.yaml
- bases/metallb.io_servicel2statuses.yaml
- bases/metallb.io_servicebgpstatuses.yaml
- bases/metallb.io_configurationstates.yaml

patches:
- path: patches/crd-conversion-patch-bgppeers.yaml
  target:
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
- path: patches/crd-conversion-patch-bgpadvertisements.yaml
  target:
    kind: CustomResourceDefinition
    name: bgpadvertisements.metallb.io
- path: patches/crd-conversion-patch-l2advertisements.yaml
  target:
    kind: CustomResourceDefinition
    name: l2advertisements.metallb.io
- path: patches/crd-conversion-patch-ipaddresspools.yaml
  target:
    kind: CustomResourceDefinition
    name: ipaddresspools.metallb.io
- path: patches/crd-conversion-patch-bfdprofiles.yaml
  target:
    kind: CustomResourceDefinition
    name: bfdprofiles.metallb.io
- path: patches/crd-conversion-patch-communities.yaml
  target:
    kind: CustomResourceDefinition
    name: communities.metallb.io
- path: patches/crd-conversion-patch-configurationstates.yaml
  target:
    kind: CustomResourceDefinition
    name: configurationstates.metallb.io
- path: patches/crd-conversion-patch-servicebgpstatuses.yaml
  target:
    kind: CustomResourceDefinition
    name: servicebgpstatuses.metallb.io
- path: patches/crd-conversion-patch-servicel2statuses.yaml
  target:
    kind: CustomResourceDefinition
    name: servicel2statuses.metallb.io
